### ISSUE TITLE
The code works , but i cant seem to punch through the NAT

### ISSUE THREAD

**Issue by yanivx4x** [moien007/STUN#1]
Hello,
I've been using the code with some success.
Like this:

`
```
if (!STUNClient.TryParseHostAndPort("stun3.l.google.com:19302", out IPEndPoint stunEndPoint))
                throw new Exception("Failed to resolve STUN server address");
```

            var queryResult = STUNClient.Query(stunEndPoint, STUNQueryType.ExactNAT, false);

            if (queryResult.QueryError != STUNQueryError.Success)
                throw new Exception("Query Error: " + queryResult.QueryError.ToString());

            Console.WriteLine("PublicEndPoint: {0}", queryResult.PublicEndPoint);
            Console.WriteLine("LocalEndPoint: {0}", queryResult.LocalEndPoint);
            Console.WriteLine("NAT Type: {0}", queryResult.NATType);`

afterwards i get a good result:
![image](https://user-images.githubusercontent.com/18504020/46259947-b69d0280-c4e8-11e8-8120-b6bb50bcdf70.png)

then i try and listen on that port:
`
  ` byte[] data = new byte[1024]; `

            Console.WriteLine("Waiting for a client...");

            while (true)
            {
                int i = socket.Receive(data);
                Console.WriteLine(System.Text.Encoding.UTF8.GetString(data));  
            }
`

but no matter what i try and from where i send ( I send to the public EndPoint) it doesnt get to me.

any ideas?
BTW by sniffing packets with wireshark i can see that the response from the STUN server is fine

**Comment by moien007** [comment]
I think issue could came from  
- My code
- Your NAT
- STUN Server

My idea is 
1. Try another STUN Server
2. Try another library or tool
3. Try debugging my codes so if there's a bug you can find it

Please tell me here if problem solved. Thanks.

**Comment by moien007** [comment]
Gotcha, your using STUN for TCP sockets. You cannot hole-punch TCP ports using STUN.
