### ISSUE TITLE
Support RFC 5389/5780

### ISSUE THREAD

**Issue by knocte** [moien007/STUN#4]
https://www.netmanias.com/en/post/techdocs/6065/nat-network-protocol/stun-rfc-3489-vs-stun-rfc-5389-5780

**Comment by moien007** [comment]
Thanks for mentioning. I'm busy it'll be nice if someone can PR it.

**Comment by knocte** [comment]
@moien007 is this fixed by https://github.com/moien007/STUN/pull/3 ?

**Comment by moien007** [comment]
> @moien007 is this fixed by #3 ?

Yes, use `STUNRfc5780` class.

**Comment by knocte** [comment]
> Yes, use STUNRfc5780 class.

Ok, thanks, but it seems this class was introduced in May, this year, but the last version on nuget is 2018.

**Comment by moien007** [comment]
> Ok, thanks, but it seems this class was introduced in May, this year, but the last version on nuget is 2018.

Sorry for answering late. You have to use the library by source-code since it's no longer maintained.

**Comment by knocte** [comment]
@moien007 well I'm interested in taking the helm; I could create CI steps that publish assets to nuget.org automatically, would you give me co-ownership of the nuget package?

**Comment by moien007** [comment]
@knocte sure.

**Comment by knocte** [comment]
Ok thanks! my username in nuget is same as in github: knocte

**Comment by moien007** [comment]
I sent you both GitHub and NuGet invites.

**Comment by knocte** [comment]
Thanks
